import Head from 'next/head'
import Image from 'next/image'
import { useAuth } from '../lib/auth';
import styles from '../styles/Home.module.css'

export default function Home() {
  const auth = useAuth();

  console.log(auth.user?.photoUrl)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Qwik Feedback
        </h1>

        {!auth.user && <button onClick={() => auth.signinWithGitHub()}>{auth?.loading ? 'Loading...' : 'Sign In With Github'}</button>}
        {!auth.user && <button onClick={() => auth.signinWithGoogle()}>{auth?.loading ? 'Loading...' : 'Sign In With Google'}</button>}
        <p>{auth.user?.email}</p>
        <Image 
          src={auth.user?.photoUrl} 
          alt=""
          width="100"
          height="100"
        />
        {auth.user && <button onClick={() => auth.signout()}>{auth?.loading ? 'Loading...' : 'Sign Out'}</button>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
