import {
  Button,
  Container,
  Flex,
  Heading,
  Spacer,
  Text,
} from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import { useAuth } from '@/lib/auth';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const auth = useAuth();

  console.log(auth.user?.photoUrl);

  return (
    <div className={styles.container}>
      <Head>
        <title>QwikFeeds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxW="1440">
          <Flex align="center">
            <Heading>
              <Image src="/logo.svg" alt="" width="100" height="100" />
            </Heading>
            <Spacer />
            <Flex border="2px" borderColor="brand.100" borderRadius="50px">
              <Image src={auth.user?.photoUrl} alt="avatar" width="50" height="50" style={{ borderRadius:"50px" }} />
            </Flex>
          </Flex>
        </Container>
        <Text>
          Current User email is: {auth.user ? auth.user?.email : 'None'}
        </Text>
        {!auth.user && (
          <Button onClick={() => auth.signinWithGitHub()}>
            {auth?.loading ? 'Loading...' : 'Sign In With Github'}
          </Button>
        )}
        {!auth.user && (
          <Button onClick={() => auth.signinWithGoogle()}>
            {auth?.loading ? 'Loading...' : 'Sign In With Google'}
          </Button>
        )}
        {auth.user ? (
          <Button onClick={() => auth.signout()}>
            {auth?.loading ? 'Loading...' : 'Sign Out'}
          </Button>
        ) : (
          <>
            <Button onClick={() => auth.signinWithGitHub()}>
              {auth?.loading ? 'Loading...' : 'Sign In With Github'}
            </Button>
            <Button onClick={() => auth.signinWithGoogle()}>
              {auth?.loading ? 'Loading...' : 'Sign In With Google'}
            </Button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
